version: '3.0.0'

services:
  api:
    image: parrotweb/exchange-rate-api:latest
    build: ./ExchangeRate.Backend/
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
  client:
    image: parrotweb/exchange-rate-client:latest
    build: ./ExchangeRate.Frontend/
    restart: always
    ports:
      - "8080:80"